name: Deploy Sphinx documentation to Pages

# Runs on pushes targeting the default branch
on:
  push:
    branches: [v3]

# Cancel any in-progress job or run
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  pages:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    - id: deployment
      uses: sphinx-notes/pages@dc3b20246f3aa36461db0a9d1a68879df0fd6cc3 # v3
